import { FC } from 'react'
import styles from '../styles/pages/Home.module.css'
import Button from '@/components/ui/Button'
import Navbar from '@/layouts/Navbar'
import Link from 'next/link'

interface HomePageProps { }

const HomePage: FC<HomePageProps> = ({ }) => {
  return (
    <div className={styles.main}>
      <Navbar />
      <section className={styles.hero_section}>
        <h1>
          A <span>360°</span> Financial Management and Education Platform
        </h1>
        <p>Empowering individuals to master personal finance, build financial literacy, and make smarter investments.</p>

        <Button style={{ fontSize: "1rem", background: "var(--active-background)", padding: "15px 30px", marginTop: "40px", borderRadius: "10px" }}><Link style={{ color: "var(--primary-color)", textDecoration: "none" }} href={"/login"}>Login/Register Now</Link></Button>
      </section>

      <section id='features' className={styles.features_div}>
        <h2>Our Key <span>Features</span></h2>
        <div className={styles.features}>

          <figure className={`${styles.features_box} ${styles.row}`}>
            <div className={styles.features_img}>
              <img src="https://res.cloudinary.com/dvk80x6fi/image/upload/v1734855622/Screenshot_1057_hlvvls.png" alt="" />
            </div>
            <figcaption className={styles.features_cap}>
              <h3>Realtime Analytics and Interactive Charts</h3>
              <p>Visualize your financial data with real-time analytics and dynamic charts. Monitor your spending, savings, and investments at a glance.</p>
            </figcaption>
          </figure>
          <figure className={`${styles.features_box} ${styles.row}`}>
            <div className={styles.features_img}>
              <img src="https://res.cloudinary.com/dvk80x6fi/image/upload/v1734855641/Screenshot_1058_npknw2.png" alt="" />
            </div>
            <figcaption className={styles.features_cap}>
              <h3>AI-Powered Expense Tracker & Savings Planner</h3>
              <p>Track your expenses effortlessly and receive personalized savings plans generated by AI to help you achieve your financial goals.</p>
            </figcaption>
          </figure>
          <figure className={`${styles.features_box} ${styles.row}`}>
            <div className={styles.features_img}>
              <img src="https://res.cloudinary.com/dvk80x6fi/image/upload/v1734855601/Screenshot_1059_x3ftgg.png" alt="" />
            </div>
            <figcaption className={styles.features_cap}>
              <h3>AI-Powered Debt Repayment Calculator</h3>
              <p>Plan and optimize your debt repayments with ease. Our AI-powered calculator suggests strategies to minimize interest and pay off debts faster.</p>
            </figcaption>
          </figure>
          <figure className={`${styles.features_box} ${styles.row}`}>
            <div className={styles.features_img}>
              <img src="https://res.cloudinary.com/dvk80x6fi/image/upload/v1734855845/Screenshot_1060_kznbyi.png" alt="" />
            </div>
            <figcaption className={styles.features_cap}>
              <h3>Learn Finance and Earn Rewards</h3>
              <p>Improve your financial knowledge with AI-driven tutorials and quizzes. Take quizzes, test your skills, and earn real rewards for learning.</p>
            </figcaption>
          </figure>


        </div>
      </section>


      <footer>
        <p>Copyright &copy; 2024; All Right Reserved</p>
      </footer>

    </div>
  )
}

export default HomePage